export ROCM_ROOT_CONDA_BACKUP=${ROCM_ROOT:-}
export ROCM_ROOT=$CONDA_PREFIX

export ROCM_PATH_CONDA_BACKUP=${ROCM_PATH:-}
export ROCM_PATH=$CONDA_PREFIX

export HCC_HOME_CONDA_BACKUP=${HCC_HOME:-}
export HCC_HOME=$CONDA_PREFIX

export HSA_PATH_CONDA_BACKUP=${HCC_PATH:-}
export HSA_PATH=$CONDA_PREFIX
